export const GithubJhan = 'https://github.com/jhangmez'
export const LinkedinHarkaysoft = 'https://www.linkedin.com/company/harkaysoft/'
export const LinkedinJhan = 'https://www.linkedin.com/in/jhangmez'
export const VercelHarkaysoft = 'https://harkaysoft.vercel.app/'
export const VercelJhan = 'https://jhangmez.vercel.app/'
export const jhangmez = 'https://jhangmez.xyz/'
